<?php

namespace CTRV\FlowBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageTypeRepository extends EntityRepository
{
}
