<?php

namespace CTRV\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventFollowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventFollowerRepository extends EntityRepository
{
}
