<?php

namespace CTRV\FlowBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GroupeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \CTRV\FlowBundle\Controller\GroupeController();
        return $instance;
    }
}
