<?php

namespace CTRV\EventBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EventCommentController__JMSInjector
{
    public static function inject($container) {
        $instance = new \CTRV\EventBundle\Controller\EventCommentController();
        return $instance;
    }
}
