<?php

namespace CTRV\CommonBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AuthController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:/cityrovers/workspace/ctrv/app/cache/dev/jms_diextra/proxies/CTRV-CommonBundle-Controller-AuthController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('CTRV\\CommonBundle\\Controller\\AuthController' => array('registerAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_ee6fac79da56355a10ef6bc08e6904ef95ba4432\__CG__\CTRV\CommonBundle\Controller\AuthController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
