<?php

namespace CTRV\CommonBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CityController__JMSInjector
{
    public static function inject($container) {
        $instance = new \CTRV\CommonBundle\Controller\CityController();
        return $instance;
    }
}
