<?php

namespace CTRV\MailBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MailController__JMSInjector
{
    public static function inject($container) {
        $instance = new \CTRV\MailBundle\Controller\MailController();
        return $instance;
    }
}
