<?php

namespace CTRV\PlaceBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PlaceCommentController__JMSInjector
{
    public static function inject($container) {
        $instance = new \CTRV\PlaceBundle\Controller\PlaceCommentController();
        return $instance;
    }
}
