<?php

namespace CTRV\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserBlackListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBlackListRepository extends EntityRepository
{
}
