<?php

namespace CTRV\PlaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TraitedPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraitedPlaceRepository extends EntityRepository
{
}
