<?php

namespace Proxies\__CG__\CTRV\CommonBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class City extends \CTRV\CommonBundle\Entity\City implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setLatitude($latitude)
    {
        $this->__load();
        return parent::setLatitude($latitude);
    }

    public function getLatitude()
    {
        $this->__load();
        return parent::getLatitude();
    }

    public function setLongitude($longitude)
    {
        $this->__load();
        return parent::setLongitude($longitude);
    }

    public function getLongitude()
    {
        $this->__load();
        return parent::getLongitude();
    }

    public function setLatitudeInf($latitudeInf)
    {
        $this->__load();
        return parent::setLatitudeInf($latitudeInf);
    }

    public function getLatitudeInf()
    {
        $this->__load();
        return parent::getLatitudeInf();
    }

    public function setLatitudeSup($latitudeSup)
    {
        $this->__load();
        return parent::setLatitudeSup($latitudeSup);
    }

    public function getLatitudeSup()
    {
        $this->__load();
        return parent::getLatitudeSup();
    }

    public function setLongitudeInf($longitudeInf)
    {
        $this->__load();
        return parent::setLongitudeInf($longitudeInf);
    }

    public function getLongitudeInf()
    {
        $this->__load();
        return parent::getLongitudeInf();
    }

    public function setLongitudeSup($longitudeSup)
    {
        $this->__load();
        return parent::setLongitudeSup($longitudeSup);
    }

    public function getLongitudeSup()
    {
        $this->__load();
        return parent::getLongitudeSup();
    }

    public function addPublicMessage(\CTRV\FlowBundle\Entity\PublicMessage $publicMessages)
    {
        $this->__load();
        return parent::addPublicMessage($publicMessages);
    }

    public function removePublicMessage(\CTRV\FlowBundle\Entity\PublicMessage $publicMessages)
    {
        $this->__load();
        return parent::removePublicMessage($publicMessages);
    }

    public function getPublicMessages()
    {
        $this->__load();
        return parent::getPublicMessages();
    }

    public function addUser(\CTRV\CommonBundle\Entity\User $users)
    {
        $this->__load();
        return parent::addUser($users);
    }

    public function removeUser(\CTRV\CommonBundle\Entity\User $users)
    {
        $this->__load();
        return parent::removeUser($users);
    }

    public function getUsers()
    {
        $this->__load();
        return parent::getUsers();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'latitude', 'longitude', 'latitudeInf', 'latitudeSup', 'longitudeInf', 'longitudeSup', 'publicMessages', 'users');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}