<?php

namespace Proxies\__CG__\CTRV\CommonBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Contact extends \CTRV\CommonBundle\Entity\Contact implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIsAccepted($isAccepted)
    {
        $this->__load();
        return parent::setIsAccepted($isAccepted);
    }

    public function getIsAccepted()
    {
        $this->__load();
        return parent::getIsAccepted();
    }

    public function setOwnerUserid(\CTRV\CommonBundle\Entity\User $ownerUserid = NULL)
    {
        $this->__load();
        return parent::setOwnerUserid($ownerUserid);
    }

    public function getOwnerUserid()
    {
        $this->__load();
        return parent::getOwnerUserid();
    }

    public function setContactPublicKey(\CTRV\CommonBundle\Entity\User $contactPublicKey = NULL)
    {
        $this->__load();
        return parent::setContactPublicKey($contactPublicKey);
    }

    public function getContactPublicKey()
    {
        $this->__load();
        return parent::getContactPublicKey();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'isAccepted', 'ownerUserid', 'contactPublicKey');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}